# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oPA_yXRZ-Kwz1Id3U2UftpjHFeHAQ8zP
"""

import cv2 
from google.colab.patches import cv2_imshow
import matplotlib.pylab as plt

img = cv2.imread('./fig2.png')
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2_imshow(gray_img)

hist = cv2.calcHist([gray_img], [0], None, [256], [0,256])
plt.plot(hist)
plt.show



{
    "Alunos": ["Paulo Leonardo da Silva Paes", "Guilherme Farias Garcia"],
    "Questão1": "A normalização do histograma é feita por um calculo do valor da ferquencia pela quantidade de pixels. Normalizar representa achar a probabilidade de um determinado tom de cinza aparecer numa imagem.",
    "Questão1": "Um histograma apresenta niveis de brilho e contras te das imagens, fazendo a normalização se as intensidades de brilho e constraste a imagens melhor vizualizavel.",
}

img_yuv = cv2.cvtColor(img, cv2.COLOR_BGR2YUV)
img_yuv[:,:,0] = cv2.equalizeHist(img_yuv[:,:,0])

hist_equal = cv2.cvtColor(img_yuv, cv2.COLOR_YUV2BGR)

cv2_imshow(img_yuv)